# scripts/auto_retrain.py
"""
Auto-retrain controller:
- Run drift detection (scripts/check_drift.py's logic)
- If decision is MILD_DRIFT or SEVERE_DRIFT, back up current model and run retrain
- Write audit log to data/retrain_log.csv
- Exit with status 0 on success (even if no retrain)
"""

import sys
import os
import json
import subprocess
from datetime import datetime
import shutil
import csv

# ensure project root is in path (important when run inside container)
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

# Paths (project-root relative)
ROOT = os.path.dirname(os.path.dirname(__file__))
DATA_DIR = os.path.join(ROOT, "data")
MODEL_DIR = os.path.join(ROOT, "models")
MODEL_PATH = os.path.join(MODEL_DIR, "traffic_model.joblib")
BACKUP_DIR = os.path.join(MODEL_DIR, "backups")
DRIFT_REPORT = os.path.join(DATA_DIR, "drift_metrics.json")
RETRAIN_LOG = os.path.join(DATA_DIR, "retrain_log.csv")

def load_drift_report():
    if not os.path.exists(DRIFT_REPORT):
        return None
    with open(DRIFT_REPORT, "r") as f:
        return json.load(f)

def run_check_drift():
    # Run the check_drift script (this will produce/update drift_metrics.json)
    # We call it via subprocess to avoid import side-effects
    print("Running drift detection...")
    res = subprocess.run(["python", "scripts/check_drift.py"], capture_output=True, text=True)
    print("check_drift stdout:")
    print(res.stdout)
    if res.returncode != 0:
        print("check_drift stderr:")
        print(res.stderr)
        raise RuntimeError("check_drift.py failed")
    # read the generated report
    report = load_drift_report()
    if report is None:
        raise FileNotFoundError("drift_metrics.json not generated by check_drift.py")
    return report

def backup_model():
    # create backup dir
    os.makedirs(BACKUP_DIR, exist_ok=True)
    if not os.path.exists(MODEL_PATH):
        print("No existing model found to backup.")
        return None
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_name = f"traffic_model_{ts}.joblib"
    backup_path = os.path.join(BACKUP_DIR, backup_name)
    shutil.copy2(MODEL_PATH, backup_path)
    print(f"Backed up model to: {backup_path}")
    return backup_path

def run_retrain():
    # Run retrain script
    print("Starting retrain...")
    res = subprocess.run(["python", "scripts/retrain.py"], capture_output=True, text=True)
    print(res.stdout)
    if res.returncode != 0:
        print("retrain stderr:")
        print(res.stderr)
        raise RuntimeError("retrain.py failed")
    print("Retrain finished successfully.")
    return True

def append_retrain_log(entry: dict):
    os.makedirs(DATA_DIR, exist_ok=True)
    header = ["timestamp", "drift_decision", "mae", "backup_path", "status", "notes"]
    file_exists = os.path.exists(RETRAIN_LOG)
    with open(RETRAIN_LOG, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=header)
        if not file_exists:
            writer.writeheader()
        writer.writerow(entry)

def main():
    try:
        report = run_check_drift()
    except Exception as e:
        print(f"Failed to run drift detection: {e}")
        # write a failed log entry
        entry = {
            "timestamp": datetime.now().isoformat(),
            "drift_decision": "CHECK_FAILED",
            "mae": "",
            "backup_path": "",
            "status": "FAILED",
            "notes": str(e)
        }
        append_retrain_log(entry)
        raise

    decision = report.get("decision", "NO_DRIFT")
    mae = report.get("mae", None)

    entry = {
        "timestamp": datetime.now().isoformat(),
        "drift_decision": decision,
        "mae": mae if mae is not None else "",
        "backup_path": "",
        "status": "NO_ACTION",
        "notes": ""
    }

    # If MILD or SEVERE -> backup + retrain
    if decision in ["MILD_DRIFT", "SEVERE_DRIFT"]:
        try:
            backup_path = backup_model() or ""
            entry["backup_path"] = backup_path
            run_retrain()
            entry["status"] = "RETRAINED"
            entry["notes"] = "Retrain triggered automatically due to drift"
        except Exception as e:
            entry["status"] = "RETRAIN_FAILED"
            entry["notes"] = str(e)
            append_retrain_log(entry)
            raise
    else:
        print("No retrain required based on decision:", decision)

    append_retrain_log(entry)
    print("Auto-retrain run complete. Log written to:", RETRAIN_LOG)

if __name__ == "__main__":
    main()
